name: Pull request comment
on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  pull_request_comment:
    if: contains(github.event.comment.html_url, '/pull/')  # Ensure comments come from PRs
    runs-on: [macos-latest]
    steps:
      - name: Deploy Debug APK
        if: contains(github.event.comment.body, '/deploy debug')
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'develop.yml',
              ref: '${{github.event.pull_request.base.ref}}'
            });

      - name: Deploy Release APK
        if: contains(github.event.comment.body, '/deploy release')
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'release.yml',  # Workflow file name
              ref: '${{ github.head_ref || github.ref_name }}'
            });

      - name: Add deploy comment
        if: contains(github.event.comment.body, '/deploy')
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Deployment initiated on branch: ${{ github.event.issue.pull_request.head.ref }}'
            });

      - name: Test
        if: contains(github.event.comment.body, '/test')
        run: |
          echo "Test command executed on branch: ${{ github.event.issue.pull_request.head.ref }}"
